### ISSUE TITLE
Reconnect Issue on 0.4.1.dev1

### ISSUE THREAD

**Issue by jmurrayufo** [isbe-house/dyscord#49]
```2021-10-27 20:30:48,078 - ERROR - discord_client.py:200 - _run - Caught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1089, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1144, in read_frame
    frame = await Frame.read(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dyscord/client/discord_client.py", line 198, in _run
    raise exception
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/dyscord/client/discord_client.py", line 251, in _web_socket_listener
    data = await websocket.recv()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent```

**Comment by jmurrayufo** [comment]
This is still observed in 0.5.1. Need more fixes.

**Comment by jmurrayufo** [comment]
> discord-bot_1    | 2021-11-06 01:23:37,970 - INFO - discord_client.py:398 - _event_dispatcher - Got a PRESENCE_UPDATE
discord-bot_1    | 2021-11-06 01:23:42,000 - INFO - discord_client.py:398 - _event_dispatcher - Got a PRESENCE_UPDATE
discord-bot_1    | 2021-11-06 01:23:58,467 - INFO - discord_client.py:398 - _event_dispatcher - Got a PRESENCE_UPDATE
discord-bot_1    | 2021-11-06 01:23:59,567 - INFO - discord_client.py:398 - _event_dispatcher - Got a PRESENCE_UPDATE
discord-bot_1    | 2021-11-06 01:25:15,110 - INFO - discord_client.py:398 - _event_dispatcher - Got a PRESENCE_UPDATE
discord-bot_1    | 2021-11-06 01:26:58,116 - CRITICAL - discord_client.py:351 - _reconnect - Try to connect to wss://gateway.discord.gg?v=9&encoding=json
discord-bot_1    | 2021-11-06 01:26:58,227 - INFO - discord_client.py:298 - _heartbeat - New heartbeat task started. Send new heartbeat NOW.
discord-bot_1    | 2021-11-06 01:49:27,898 - CRITICAL - discord_client.py:351 - _reconnect - Try to connect to wss://gateway.discord.gg?v=9&encoding=json
discord-bot_1    | 2021-11-06 01:49:27,987 - INFO - discord_client.py:298 - _heartbeat - New heartbeat task started. Send new heartbeat NOW.
